### ISSUE TITLE
check_tails error

### ISSUE THREAD

**Issue by kayla-xu** [LRB-IIMCB/ninetails#11]
hello, I had a problem with the check_tails step, and the code was

> results <- ninetails::check_tails(
>   nanopolish = system.file('extdata', 
>                            'test_data', 
>                            'nanopolish_output.tsv', 
>                            package = 'ninetails'),
>   sequencing_summary = system.file('extdata', 
>                                    'test_data', 
>                                    'sequencing_summary.txt', 
>                                    package = 'ninetails'),
>   workspace = system.file('extdata', 
>                           'test_data', 
>                           'basecalled_fast5', 
>                           package = 'ninetails'),
>   num_cores = 2,
>   basecall_group = 'Basecall_1D_000',
>   pass_only=TRUE,
>   save_dir = './')

the error message is

> Welcome to Ninetails 1.0.2
> 
> [2024-07-26 21:30:43]  Ninetails was launched with following options:
>  nanopolish output file:       /mnt/data3/xuzijie/package/ninetails/extdata/test_data/nanopolish_output.tsv
>  sequencing sumary file:       /mnt/data3/xuzijie/package/ninetails/extdata/test_data/sequencing_summary.txt
>  fast5 files directory:        /mnt/data3/xuzijie/package/ninetails/extdata/test_data/basecalled_fast5
>  number of cores:              2
>  basecall group:               Basecall_1D_000
>  only "PASS" reads included:   TRUE
>  output quality control:       TRUE
>  output directory:             /mnt/raid61/Personal_data/xuzijie/task/04DRS/02result/Mettle3/
> 
> 
> [2024-07-26 21:30:43] Pipeline initialized
> 
> [2024-07-26 21:30:43] Found 1 fast5 file(s) in provided directory.
> [2024-07-26 21:30:43] Analyzing one of the given fast5 files to check
> if the data are in required format...
>   Previewed fast5 file parameters:
>     data type: RNA
>     fast5 file type: multifast5
>     basecaller used: ONT Guppy basecalling software.
>     basecaller version: 6.0.6+8a98bbcbd
>     basecalling model: flipflop
> 
> [2024-07-26 21:30:44] Extracting features of provided reads...
>   |==================================================| 100%
> Produced feature list is of length 0. Check your input (nanopolish, fast5 files) for integrity.
> [2024-07-26 21:30:44] Ninetails aborted.

I have tried my own data, and the same result, I have checked that the data exists, looking forward to getting your reply！！！

**Comment by nemitheasura** [comment]
Hi, 

thank you for using ninetails. This error might also indicate that the ninetails was unable to iterate through the fast5 files for some reason. To diagnose your problem, I will ask a few questions:

1. Are all R dependencies properly loaded into your session? By this, I mean reticulate and rhdf5 packages.
2. Is VBZ plugin installed and added to the path?
3. Is file locking disabled in rhdf5? 

Quick debugging:
If all deps are available and properly loaded, try this:

1. Check if you are able to open any fast5 file from within R/Rstudio using rhdf5. If not, then the problem is caused by rhdf5 malfunction. Reinstall, retry accessing fast5. 

2. Execute rhdf5::h5disableFileLocking() before launching the check_tails(). Try again on test built-in data. Is error still persisting?

If the problem persists, please try to launch the following code:

```
polya_summary <- ninetails::extract_polya_data(
  nanopolish = system.file('extdata', 
                           'test_data', 
                           'nanopolish_output.tsv', 
                           package = 'ninetails'),
  sequencing_summary = system.file('extdata', 
                                   'test_data', 
                                   'sequencing_summary.txt', 
                                   package = 'ninetails'),
  pass_only = TRUE)
  
  dummy_tail <- ninetails::extract_tail_data(
  readname="1e6c551d-3ba7-461e-b930-4c87f5d638ba",
  polya_summary = polya_summary,
  workspace = system.file('extdata', 
                          'test_data', 
                          'basecalled_fast5', 
                          package = 'ninetails'),
  basecall_group = 'Basecall_1D_000')
```

Please provide me the content of the resulting polya_summary and dummy_tail variables, so I can debug. 

Please let me know how it went. 

Best,
N.

**Comment by kayla-xu** [comment]
Yes, we do! I have solved the problem according to your suggestion, thank you very much！！！

**Comment by nemitheasura** [comment]
Glad I could help. 
Case closed, then.
