### ISSUE TITLE
Ninetails check_tails results in error: Produced feature list is of length 0.

### ISSUE THREAD

**Issue by zigavicic** [LRB-IIMCB/ninetails#5]
Hi,

So I've tried running ninetails on my dataset with the code below:

`

    results <- ninetails::check_tails(
        nanopolish = "/nanopolish_polya.tsv", #Result of nanopolish polya function
        sequencing_summary = "/sequencing_summary.txt",
        workspace = "/workspace", #Where the basecalled fast5 files are
        num_cores = 8,
        basecall_group = 'Basecall_1D_000',
        pass_only = TRUE,
        save_dir = '/results')

`
Which results in: 

> 
Welcome to Ninetails 0.6.0

[2023-01-09 07:11:20]  Ninetails was launched with following options:
 nanopolish output file:       /nanopolish_polya.tsv
 sequencing sumary file:       /sequencing_summary.txt
 fast5 files directory:        /workspace
 number of cores:              8
 basecall group:               Basecall_1D_000
 only "PASS" reads included:   TRUE
 output quality control:       TRUE
 output directory:             /results

[2023-01-09 07:11:20] Pipeline initialized

[2023-01-09 07:11:21] Found 235 fast5 file(s) in provided directory.
[2023-01-09 07:11:22] Analyzing one of the given fast5 files to check
if the data are in required format... 
  Previewed fast5 file parameters:
    data type: RNA 
    fast5 file type: multifast5 
    basecaller used: ONT Guppy basecalling software.  
    basecaller version: 6.3.8+d9e0f648d  
    basecalling model: flipflop  
  
[2023-01-09 07:11:28] Extracting features of provided reads...
|==================================================| 100%
Error: Produced feature list is of length 0. Check your input (nanopolish, fast5 files) for integrity. Execution halted

It is unclear to me what may cause the error as the fast5 and nanopolish files seem to be okay cause they work with other programs that use similar strategies to infer RNA modifications from basecalled fast5 reads.

**Comment by nemitheasura** [comment]
Hi @zigavicic, 

thank you for using ninetails. This error may be caused due to a few reasons. Without the reprex, I can say for certain that ninetails could not find/extract some data categories from your fast5 files. 

 Could you have a look into one of your fast5 files and check, whether the necessary categories are present? 
 Namely, whether the "Move" is present in /Analyses/Basecall_1D_000/BaseCalled_template/ or not. 
 
 You can check this with HDF5Viewer or with h5dump <fast5filename> | less in terminal. 
 
 Currently available version of ninetails requires "Move" table to operate. Your version of Guppy most likely does not store this data matrix in the fast5 output. If it is the case, than the quickest possible solution (temporary) is to re-basecall your data with lower version of Guppy basecaller (6.0.0 for instance - I am sure that it produces "Move" in the output) and re-run the pipeline with this dataset, updating the basecall group accordingly.  Sorry for the inconvenience.

If it is not the case - can you send me a small reprex?

**Comment by zigavicic** [comment]
Hi @nemitheasura

the fast5 files do contain Move category. Please find the necessary files to reproduce the error uploaded here: https://bit.ly/3imxf2V

Thanks!

**Comment by zigavicic** [comment]
Re-ran basecalling using Guppy v6.0.0. resulting in the same output error.

**Comment by zigavicic** [comment]
Sorry, seems like I built the environment for ninetails the wrong way. I went back and followed your instructions on moving the VBZ plugin into the correct library directory. Could you provide a build that comes with all the dependecies or maybe a Docker image that would enable easier use of this tool? It's quite difficult to build a working environment, especially because of the need to export VBZ plugin into the correct path and also installing the tensorflow dependencies. I expect to have first results aftter (hopefully) establishing a working environment tomorrow, and I will edit this to let you know if everything works fine.
